import type { OperationDescriptor } from './types'

export const operations: OperationDescriptor[] = [
  {
    id: 'json-format',
    name: 'JSON Format / Validate',
    description: 'Format, minify, and validate JSON.',
    category: 'format',
    aliases: ['json', 'prettify', 'minify'],
    directions: ['format', 'minify', 'validate'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'html-format',
    name: 'HTML Beautify / Minify',
    description: 'Format or minify HTML without executing it.',
    category: 'format',
    aliases: ['html', 'markup'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'css-format',
    name: 'CSS Beautify / Minify',
    description: 'Format or minify CSS.',
    category: 'format',
    aliases: ['css', 'stylesheet'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'javascript-format',
    name: 'JavaScript Beautify / Minify',
    description: 'Format JavaScript source as text.',
    category: 'format',
    aliases: ['js', 'javascript'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'erb-format',
    name: 'ERB Beautify / Minify',
    description: 'Indent ERB markup without executing templates.',
    category: 'format',
    aliases: ['erb', 'ruby template'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'less-format',
    name: 'LESS Beautify / Minify',
    description: 'Format LESS source without compiling it.',
    category: 'format',
    aliases: ['less'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'scss-format',
    name: 'SCSS Beautify / Minify',
    description: 'Format SCSS source without compiling it.',
    category: 'format',
    aliases: ['sass', 'scss'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'xml-format',
    name: 'XML Beautify / Minify',
    description: 'Format or minify XML as inert text.',
    category: 'format',
    aliases: ['xml'],
    directions: ['format', 'minify'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'sql-format',
    name: 'SQL Formatter',
    description: 'Format SQL with an explicit dialect.',
    category: 'format',
    aliases: ['sql', 'query'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'line-sort',
    name: 'Line Sort / Dedupe',
    description: 'Sort lines and optionally remove duplicates.',
    category: 'format',
    aliases: ['sort', 'dedupe', 'lines'],
    securityProfile: 'pure',
    pack: 2,
  },

  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Inspect URL components and query parameters.',
    category: 'convert',
    aliases: ['url', 'query string'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    description: 'Convert YAML to JSON.',
    category: 'convert',
    aliases: ['yaml', 'json'],
    securityProfile: 'parser',
    pack: 2,
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON to YAML.',
    category: 'convert',
    aliases: ['yaml', 'json'],
    securityProfile: 'parser',
    pack: 2,
  },
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert integers between bases 2 and 36.',
    category: 'convert',
    aliases: ['binary', 'octal', 'decimal', 'hex'],
    securityProfile: 'pure',
    pack: 2,
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert an array of objects to RFC 4180-style CSV.',
    category: 'convert',
    aliases: ['csv', 'json'],
    securityProfile: 'parser',
    pack: 2,
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV rows to JSON objects.',
    category: 'convert',
    aliases: ['csv', 'json'],
    securityProfile: 'parser',
    pack: 2,
  },
  {
    id: 'html-to-jsx',
    name: 'HTML to JSX',
    description: 'Convert common HTML attributes to JSX.',
    category: 'convert',
    aliases: ['jsx', 'react', 'html'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'string-case',
    name: 'String Case Converter',
    description: 'Convert text to common identifier and title cases.',
    category: 'convert',
    aliases: ['camel', 'snake', 'kebab', 'title'],
    securityProfile: 'pure',
    pack: 2,
  },
  {
    id: 'php-to-json',
    name: 'PHP to JSON',
    description: 'Parse a safe subset of PHP array syntax into JSON.',
    category: 'convert',
    aliases: ['php', 'json'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'json-to-php',
    name: 'JSON to PHP',
    description: 'Convert JSON data to inert PHP array syntax.',
    category: 'convert',
    aliases: ['php', 'json'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'php-serialize',
    name: 'PHP Serializer',
    description: 'Serialize JSON-compatible data in PHP format.',
    category: 'convert',
    aliases: ['php', 'serialize'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'php-unserialize',
    name: 'PHP Unserializer',
    description: 'Parse PHP serialized scalar, array, and object-like data without PHP.',
    category: 'convert',
    aliases: ['php', 'unserialize'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'svg-to-css',
    name: 'SVG to CSS',
    description: 'Create an encoded CSS background-image from SVG.',
    category: 'convert',
    aliases: ['svg', 'css', 'data url'],
    securityProfile: 'parser',
    pack: 3,
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code',
    description: 'Parse a cURL command without executing it and emit code.',
    category: 'convert',
    aliases: ['curl', 'http', 'request'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'json-to-code',
    name: 'JSON to Code',
    description: 'Infer a root model for common programming languages.',
    category: 'convert',
    aliases: ['types', 'interface', 'struct'],
    securityProfile: 'parser',
    pack: 4,
  },
  {
    id: 'hex-to-ascii',
    name: 'Hex to ASCII',
    description: 'Decode hexadecimal bytes.',
    category: 'convert',
    aliases: ['hex', 'ascii'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'ascii-to-hex',
    name: 'ASCII to Hex',
    description: 'Encode text as hexadecimal UTF-8 bytes.',
    category: 'convert',
    aliases: ['hex', 'ascii'],
    securityProfile: 'pure',
    pack: 1,
  },

  {
    id: 'unix-time',
    name: 'Unix Time Converter',
    description: 'Convert Unix seconds, milliseconds, microseconds, or nanoseconds.',
    category: 'inspect',
    aliases: ['epoch', 'timestamp', 'date'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'jwt-debugger',
    name: 'JWT Debugger',
    description: 'Decode JWT header and payload without claiming signature verification.',
    category: 'inspect',
    aliases: ['jwt', 'jws', 'token'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'regex-tester',
    name: 'RegExp Tester',
    description: 'Test a regular expression with bounded input.',
    category: 'inspect',
    aliases: ['regex', 'regexp'],
    securityProfile: 'parser',
    pack: 2,
  },
  {
    id: 'html-preview',
    name: 'HTML Preview',
    description: 'Preview HTML in a scriptless, network-blocked sandbox.',
    category: 'inspect',
    aliases: ['html', 'preview'],
    securityProfile: 'preview',
    pack: 4,
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts line by line.',
    category: 'inspect',
    aliases: ['diff', 'compare'],
    securityProfile: 'pure',
    pack: 2,
  },
  {
    id: 'string-inspector',
    name: 'String Inspector',
    description: 'Inspect UTF-8 bytes, code points, length, and whitespace.',
    category: 'inspect',
    aliases: ['unicode', 'bytes', 'code points'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Render a safe Markdown subset with raw HTML escaped.',
    category: 'inspect',
    aliases: ['markdown', 'md'],
    securityProfile: 'preview',
    pack: 2,
  },
  {
    id: 'cron-parser',
    name: 'Cron Job Parser',
    description: 'Explain a five- or six-field cron expression.',
    category: 'inspect',
    aliases: ['cron', 'schedule'],
    securityProfile: 'parser',
    pack: 1,
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert CSS hex and rgb colors.',
    category: 'inspect',
    aliases: ['color', 'hex', 'rgb', 'hsl'],
    securityProfile: 'pure',
    pack: 3,
  },

  {
    id: 'uuid-ulid-generator',
    name: 'UUID / ULID Generate / Decode',
    description: 'Generate UUID v4, UUID v7, or ULID and inspect existing IDs.',
    category: 'generate',
    aliases: ['uuid', 'ulid', 'id'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate deterministic placeholder paragraphs.',
    category: 'generate',
    aliases: ['lorem', 'placeholder'],
    securityProfile: 'pure',
    pack: 3,
  },
  {
    id: 'qr-code',
    name: 'QR Code Reader / Generator',
    description: 'Generate QR images and decode supplied pixel data locally.',
    category: 'generate',
    aliases: ['qr', 'barcode'],
    securityProfile: 'parser',
    pack: 2,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate common cryptographic and legacy digests locally.',
    category: 'generate',
    aliases: ['sha', 'md5', 'keccak', 'hash'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'random-string',
    name: 'Random String Generator',
    description: 'Generate random strings, passwords, Nano IDs, or license groups.',
    category: 'generate',
    aliases: ['random', 'password', 'nanoid'],
    securityProfile: 'pure',
    pack: 3,
  },

  {
    id: 'base64-string',
    name: 'Base64 String Encode / Decode',
    description: 'Encode or decode Base64 and Base64URL text.',
    category: 'encode',
    aliases: ['base64', 'base64url'],
    directions: ['encode', 'decode'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'base64-image',
    name: 'Base64 Image Encode / Decode',
    description: 'Create or inspect image data URLs locally.',
    category: 'encode',
    aliases: ['base64', 'image', 'data url'],
    directions: ['encode', 'decode'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'url-codec',
    name: 'URL Encode / Decode',
    description: 'Encode or decode URL components.',
    category: 'encode',
    aliases: ['url', 'percent'],
    directions: ['encode', 'decode'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'html-entity',
    name: 'HTML Entity Encode / Decode',
    description: 'Encode or decode HTML entities as text.',
    category: 'encode',
    aliases: ['html', 'entity'],
    directions: ['encode', 'decode'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'backslash-codec',
    name: 'Backslash Escape / Unescape',
    description: 'Escape or unescape common backslash sequences.',
    category: 'encode',
    aliases: ['escape', 'backslash'],
    directions: ['escape', 'unescape'],
    securityProfile: 'pure',
    pack: 1,
  },
  {
    id: 'x509-decoder',
    name: 'Certificate Decoder (X.509)',
    description: 'Inspect a PEM or DER X.509 certificate locally.',
    category: 'encode',
    aliases: ['certificate', 'pem', 'x509', 'tls'],
    securityProfile: 'parser',
    pack: 1,
  },
]

export const operationById = new Map(operations.map((operation) => [operation.id, operation]))

if (operations.length !== 47 || operationById.size !== 47) {
  throw new Error(
    `Operation registry must contain exactly 47 unique tools; got ${operations.length}/${operationById.size}`,
  )
}
